@startuml "Sub-Use Case Initialisation"

scale 2
skinparam defaultFontName "Arial"
hide footbox


control Angular as A
participant SubComponentX as S
participant FabricUIModel  as F


A -> S : constructor
activate S #LightGray

S->F : getUiModelX(...)
activate F #LightYellow

create UIModelX as U
F->U : new
activate U #LightSkyBlue
create langInfoKeeper as L
U->L : new
create masterDataKeeper as M
U->M : new
return IUIModel
return IUIModel
deactivate U
deactivate F


S->U : getUILanguageData()
activate U #LightSkyBlue


U->L : getLanguageData(...)
activate L #LightSeaGreen
return IUILanguageData

return IUILanguageData

S->S: set language sata
activate S #Grey
deactivate S

S->U: getMasterData()
activate U #LightSkyBlue
U->M : getMasterData(...)
activate M #LightGoldenRodYellow

return IMasterData
return IMasterData

S->S: set master sata
activate S #Grey
deactivate S

@enduml
